---
title: "OLASI BÜYÜK İSTANBUL DEPREMİNDE OLUŞABİLECEK ZARARLAR VE ALINMASI GEREKEN ÖNLEMLER"
author: 
  - Kaan Berk Akdere[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 20080254, [GithubRepo](https://github.com/KaanAkdere/arasinav)





# Giriş
İstanbul geçmiş dönemlerde çok sayıda yıkıcı depremlere sahne olmuştur. Kayıtlarda Bizans döneminde şehirde yıkıma neden olan yaklaşık 26 depremin yaşandığı görülmektedir. Osmanlı döneminde meydana gelen birçok deprem ve yakın zamanda yaşanan 1999 depremi şehirde ciddi harabiyete ve çok sayıda can kaybına yol açmıştır. Yapılan çalışmalar Ana Marmara Fayı’nın yakın geçmişte kırılmamış segmentlerinde yoğun bir sismik enerji biriktiğini ve İstanbul’u şiddetli bir depremin beklediğini ortaya koymaktadır. İstanbul’un gerek ülkemiz gerek tüm dünya için taşıdığı önem göz önüne alınarak şehrin deprem öncesi ve sonrasına hazırlanması önem arzetmektedir. (@csimcsek2021big) Bu çalışmamızda İstanbul Büyükşehir Belediyesi tarafından yayınlanan olası bir 7.5 mw büyüklüğündeki depremin çeşitli analiz sonuçlarının ortaya konduğu 960 gözlemli verisetinin içerisinden eleme usulü ile genel bir tablo ortaya koyup, ortaya çıkabilecek hasarları ve bunların önlenmesi için alınabilecek tedbirleri ele alacağız.


## Çalışmanın Amacı
Çalışamamızda olası büyük İstanbul depreminin ne kadar kişiyi etkileyeceğini ve sebep olacağı olası can kayıplarını belirleyeceğiz. Aynı zamanda şehirdeki alt ve üst yapıla (ev, okul, işyeri, hastane, kültürel ve tarihi mekanlar,endüstriyel tesisler) ne derece bir zarar verme riski olduğunu ve bu risklerin azaltılması için nasıl tedbirler alınması gerektiğini ortaya koyacağız.

## Literatür 
Dünyada olduğu gibi ülkemizde de,kentlerde nüfus artışı ve yapılaşmanın hızlı yoğun ve de karmaşık halde gelişmesi nedenleriyle depremler büyük can ve mal kayıpları meydana getirmektedirler Doğal afetler içinde depremler verdikleri zararlar (%60) nedeniyle ön sırada yer alır. Ülkelerin ve kentlerin depreme hazırlıklı olabilmeleri için olası depremlerin yerleri, derinlikleri, kente yakınlıkları ve kentin zemin durumu dikkate alınarak yapılacak
çok yönlü çalışmalar ve çeşitli organizasyonlarla ortaya konmalıdır.(@iskenderouglu2003istanbul)Istanbul’da ortalama 800,000 adet bina bulunmaktadır. Hem şiddet hem de spektral deplasman bazlı yer hareketi ve hasargörebilirlik analizleri kullanılarak yapılan belirlemeler toplam 35,000 ile 40,000(toplam bina stoğunun % 5’i) binanın tamamen hasar göreceğini göstermektedir.70,000 binanın ağır hasar,200,000 binanın ise orta hasar göreceği tahmin edilmektedir.Can kayıplarının 30,000 ile 40,000 arasında değişeceği tahmin edilmektedir. Hastane bakımı
gerektirecek yaralı sayısı 120,000 civarında olacaktır. Şiddet bazlı analiz sonucuna göre toplam 600,000
ailenin, spektral bazlı çalışmaya göre de 430,000 ailenin deprem sonrası acil barınma ihtiyacı doğacağı beklenmektedir.(@erdik2008earthquake) Ayrıca meydana gelmesi beklenen büyük depremden dolayı,İstanbul kentinin eşsiz tarih ve kültür mirası çok ciddi bir deprem tehditi altındadır.Aynı zamanda şehrin altyapısında da muhtemel tehditler bulunmaktadır.Şehirde bulunan 480 köprünün yaklaşık olarak %5'inde tabliye düşmesi sonucunda hasara uğrasması muhtemel olarak değerlendirilmiştir.İstanbul metropol alanı içinde yer alan doğalgaz sistemi boru hatlarında hasar meydana geleceği tahmin edilmektedir. En çok hasarın Fatih ve Güngören semtlerinde oluşması beklenmektedir.Aynı zamanda  İstanbul yakınlarında M7+ büyüklüğünde bir depremin olması durumunda kentteki endüstriyel tesislerede zarar vereceği düşünülmektedir. Tesislerin ağırlıklı olarak bulunduğu bölgelerde, deprem şiddetinin VIIIIX seviyelerine ulaşması beklenmektedir.Kentteki endüstriyel deprem riski konusunda farklı endüstriyel sektörleri kapsayacak şekilde yapılan çalışmalar, IX deprem şiddet bölgesinde makine-ekipman kayıplarının %2-%30 arasında, stok kayıplarının ise %2-%35 arasında gerçekleşebileceğini
göstermektedir.Ayrıca olası bu depremde oluşacak mali kayıp ise oldukça fazladır.Beklen toplam ekonomik kayıbın yaklaşık olarak 40-60 milyar ABD doları olması beklenmektedir.{@kayaistanbulda}.Beklenen depremde gerçekleşecek bütün bu sonuçların azaltılması için öncelikli risklerin belirlenmesi ve takiben risklerin minimum düzeye indirilmesi konusu hem istanbul hem de Türkiye için öncelikli meselelerden birisidir.



\newpage
# Kaynakça {#references}


